package MiniProjectOOP;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class HotelReservation extends javax.swing.JFrame {

    DefaultTableModel model;
    MySQLDBCustomer myDB;

    public HotelReservation() {
        initComponents();
        model = (DefaultTableModel) tblData.getModel();
        myDB = new MySQLDBCustomer();
        loadCustomerData();
    }

    void loadCustomerData() {
        try {
            String sql = "SELECT*FROM customer";
            ArrayList<Customer> list = myDB.selectQuery(sql);
            for (Customer customer : list) {
                String[] rowData = {customer.getId(), customer.getName(), customer.getSurname(), customer.getRoomType(),
                    customer.getPeriod(), customer.getDays(), customer.getTotalPrice()};
                model.addRow(rowData);
                tblData.setModel(model);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rdoSuperior = new javax.swing.JRadioButton();
        rdoDeluxe = new javax.swing.JRadioButton();
        rdoGrandDeluxe = new javax.swing.JRadioButton();
        rdoJuniorSuit = new javax.swing.JRadioButton();
        rdoGrandFamilySuite = new javax.swing.JRadioButton();
        rdoFamilyJuniorSuit = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnDays = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarResult = new javax.swing.JTextArea();
        cbxWeek = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Reservation");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("คำนวณค่าที่พัก");

        tblData.setBackground(new java.awt.Color(213, 247, 213));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name ", "Surname", "Room Type", "Period", "Days", "Total Price"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);
        if (tblData.getColumnModel().getColumnCount() > 0) {
            tblData.getColumnModel().getColumn(0).setResizable(false);
            tblData.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblData.getColumnModel().getColumn(3).setResizable(false);
            tblData.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblData.getColumnModel().getColumn(4).setResizable(false);
            tblData.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblData.getColumnModel().getColumn(5).setResizable(false);
            tblData.getColumnModel().getColumn(5).setPreferredWidth(20);
            tblData.getColumnModel().getColumn(6).setResizable(false);
            tblData.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Customer Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Customer ID :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Customer Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Customer Surname :");

        txtId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        txtSurname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSurnameKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(txtName)
                    .addComponent(txtSurname))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "ประเภทห้องพัก", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        rdoSuperior.setBackground(new java.awt.Color(204, 255, 255));
        btnGroup.add(rdoSuperior);
        rdoSuperior.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdoSuperior.setText("Superior");

        rdoDeluxe.setBackground(new java.awt.Color(204, 255, 255));
        btnGroup.add(rdoDeluxe);
        rdoDeluxe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdoDeluxe.setText("Deluxe");

        rdoGrandDeluxe.setBackground(new java.awt.Color(204, 255, 255));
        btnGroup.add(rdoGrandDeluxe);
        rdoGrandDeluxe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdoGrandDeluxe.setText("Grand Deluxe");

        rdoJuniorSuit.setBackground(new java.awt.Color(204, 255, 255));
        btnGroup.add(rdoJuniorSuit);
        rdoJuniorSuit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdoJuniorSuit.setText("Junior Suit");

        rdoGrandFamilySuite.setBackground(new java.awt.Color(204, 255, 255));
        btnGroup.add(rdoGrandFamilySuite);
        rdoGrandFamilySuite.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdoGrandFamilySuite.setText("Grand Family Suite");

        rdoFamilyJuniorSuit.setBackground(new java.awt.Color(204, 255, 255));
        btnGroup.add(rdoFamilyJuniorSuit);
        rdoFamilyJuniorSuit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdoFamilyJuniorSuit.setText("Family Junior Suit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoGrandDeluxe)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoDeluxe)
                            .addComponent(rdoSuperior))
                        .addGap(36, 36, 36)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoGrandFamilySuite)
                    .addComponent(rdoJuniorSuit)
                    .addComponent(rdoFamilyJuniorSuit))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdoJuniorSuit)
                        .addGap(18, 18, 18)
                        .addComponent(rdoFamilyJuniorSuit)
                        .addGap(18, 18, 18)
                        .addComponent(rdoGrandFamilySuite))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdoSuperior)
                        .addGap(18, 18, 18)
                        .addComponent(rdoDeluxe)
                        .addGap(18, 18, 18)
                        .addComponent(rdoGrandDeluxe)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("ช่วงที่เข้าพัก");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("จำนวนวันเข้าพัก");

        spnDays.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        spnDays.setModel(new javax.swing.SpinnerNumberModel(0, 0, 366, 1));
        spnDays.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spnDaysKeyTyped(evt);
            }
        });

        tarResult.setEditable(false);
        tarResult.setColumns(20);
        tarResult.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tarResult.setRows(5);
        jScrollPane2.setViewportView(tarResult);

        cbxWeek.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbxWeek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a period of stay", "Weekday (Sun - Thu)", "Weekend (Fri - Sat)", "Long Weekend" }));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("วัน");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("ผลการคำนวณ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addGap(33, 33, 33)
                                                    .addComponent(spnDays, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel7))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addGap(31, 31, 31)
                                                    .addComponent(cbxWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(jLabel1)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnDays, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addComponent(btnUpdate))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String roomType = "";
        int price = 0;
        String id = txtId.getText();
        String name = txtName.getText();
        String surname = txtSurname.getText();
        String period = cbxWeek.getSelectedItem().toString();
        int days = (int) spnDays.getValue();
        if (id.length() > 0 && name.length() > 0 && surname.length() > 0 && days != 0
                && cbxWeek.getSelectedIndex() != 0 && btnGroup.getSelection() != null) {
            if (rdoSuperior.isSelected()) {
                roomType = "Superior";
                if (cbxWeek.getSelectedIndex() == 1) {
                    price = 2090;
                } else if (cbxWeek.getSelectedIndex() == 2) {
                    price = 2490;
                } else {//LongWeekend
                    price = 3390;
                }
            } else if (rdoDeluxe.isSelected()) {
                roomType = "Deluxe";
                if (cbxWeek.getSelectedIndex() == 1) {
                    price = 2290;
                } else if (cbxWeek.getSelectedIndex() == 2) {
                    price = 2790;
                } else {//LongWeekend
                    price = 3690;
                }
            } else if (rdoGrandDeluxe.isSelected()) {
                roomType = "Grand Deluxe";
                if (cbxWeek.getSelectedIndex() == 1) {
                    price = 3890;
                } else if (cbxWeek.getSelectedIndex() == 2) {
                    price = 4490;
                } else {//LongWeekend
                    price = 5390;
                }
            } else if (rdoJuniorSuit.isSelected()) {
                roomType = "Junior Suit";
                if (cbxWeek.getSelectedIndex() == 1) {
                    price = 3190;
                } else if (cbxWeek.getSelectedIndex() == 2) {
                    price = 3890;
                } else {//LongWeekend
                    price = 4790;
                }
            } else if (rdoFamilyJuniorSuit.isSelected()) {
                roomType = "Family Junior Suit";
                if (cbxWeek.getSelectedIndex() == 1) {
                    price = 3990;
                } else if (cbxWeek.getSelectedIndex() == 1) {
                    price = 4690;
                } else {//LongWeekend
                    price = 5690;
                }
            } else if (rdoGrandFamilySuite.isSelected()) {
                roomType = "Grand Family Suite";
                if (cbxWeek.getSelectedIndex() == 1) {
                    price = 4690;
                } else if (cbxWeek.getSelectedIndex() == 2) {
                    price = 5590;
                } else {//LongWeekend
                    price = 6490;
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "กรุณาเลือกประเภทห้องพักครับ");
            }
            int total = price * days;
            String rowData[] = {id, name, surname, roomType, period, String.valueOf(days), String.valueOf(total)};
            String sql = "INSERT INTO customer VALUES ('" + id + "','" + name + "','" + surname + "',"
                    + "'" + roomType + "','" + period + "','" + days + "','" + total + "')";
            int row = myDB.CUD(sql);
            if (row > 0) {
                model.addRow(rowData);
                tarResult.setText("ประเภทห้องพัก : " + roomType + "\n" + "ช่วงที่เข้าพัก : " + period + "\n"
                        + "จำนวนวันเข้าพัก : " + days + " วัน" + "\n" + "รวมราคา : " + total + " บาท");
                btnAdd.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "ไม่สามารถเพิ่มข้อมูลได้");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "กรุณากรอกข้อมูลให้ครบก่อนครับ");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String result = "";
        int price = 0;
        int select = 0;
        String id, name, surname, period;
        int days;
        if (tblData.getSelectedRow() >= 0) {
            select = tblData.getSelectedRow();
            id = tblData.getValueAt(select, 0).toString();
            name = txtName.getText();
            surname = txtSurname.getText();
            period = cbxWeek.getSelectedItem().toString();
            days = (int) spnDays.getValue();
            if (rdoSuperior.isSelected()) {
                result = "Superior";
                if (cbxWeek.getSelectedIndex() == 1) {
                    price = 2090;
                } else if (cbxWeek.getSelectedIndex() == 2) {
                    price = 2490;
                } else {//LongWeekend
                    price = 3390;
                }
            } else if (rdoDeluxe.isSelected()) {
                result = "Deluxe";
                if (cbxWeek.getSelectedIndex() == 1) {
                    price = 2290;
                } else if (cbxWeek.getSelectedIndex() == 2) {
                    price = 2790;
                } else {//LongWeekend
                    price = 3690;
                }
            } else if (rdoGrandDeluxe.isSelected()) {
                result = "Grand Deluxe";
                if (cbxWeek.getSelectedIndex() == 1) {
                    price = 3890;
                } else if (cbxWeek.getSelectedIndex() == 2) {
                    price = 4490;
                } else {//LongWeekend
                    price = 5390;
                }
            } else if (rdoJuniorSuit.isSelected()) {
                result = "Junior Suit";
                if (cbxWeek.getSelectedIndex() == 1) {
                    price = 3190;
                } else if (cbxWeek.getSelectedIndex() == 2) {
                    price = 3890;
                } else {//LongWeekend
                    price = 4790;
                }
            } else if (rdoFamilyJuniorSuit.isSelected()) {
                result = "Family Junior Suit";
                if (cbxWeek.getSelectedIndex() == 1) {
                    price = 3990;
                } else if (cbxWeek.getSelectedIndex() == 1) {
                    price = 4690;
                } else {//LongWeekend
                    price = 5690;
                }
            } else if (rdoGrandFamilySuite.isSelected()) {
                result = "Grand Family Suite";
                if (cbxWeek.getSelectedIndex() == 1) {
                    price = 4690;
                } else if (cbxWeek.getSelectedIndex() == 2) {
                    price = 5590;
                } else {//LongWeekend
                    price = 6490;
                }
            }
            int total = price * days;
            String sql = "UPDATE customer SET Customer_Name = '" + name + "', "
                    + "Customer_Surname ='" + surname + "',Room_Type='" + result + "' "
                    + ",Period='" + period + "',Days='" + days + "',Total_Price='" + total + "' "
                    + "WHERE Customer_ID= '" + id + "';";
            int updRow = myDB.CUD(sql);
            if (updRow > 0) {
                tblData.setValueAt(name, select, 1);
                tblData.setValueAt(surname, select, 2);
                tblData.setValueAt(result, select, 3);
                tblData.setValueAt(period, select, 4);
                tblData.setValueAt(days, select, 5);
                tblData.setValueAt(total, select, 6);
                clearText();
            } else {
                JOptionPane.showMessageDialog(rootPane, "ไม่สามารถแก้ไขข้อมูลได้ครับ");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "เลือกเเถวข้อมูลก่อนแก้ไขครับ");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tblData.getSelectedRow();
        if (row >= 0) {
            String id = tblData.getValueAt(row, 0).toString();
            String sql = "DELETE FROM customer WHERE Customer_ID='" + id + "'";
            int delRow = myDB.CUD(sql);
            if (delRow > 0) {
                model.removeRow(tblData.getSelectedRow());
                clearText();
            } else {
                JOptionPane.showMessageDialog(rootPane, "ไม่สามารถลบข้อมูลได้ครับ");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "เลือกแถวข้อมูลก่อนลบครับ");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearText();
        btnAdd.setEnabled(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "Do you want to Exit ?");
        if (option == JOptionPane.YES_OPTION) {
            new Menu().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        btnAdd.setEnabled(false);
        int row = tblData.getSelectedRow();
        if (row >= 0) {
            String id = tblData.getValueAt(row, 0).toString();
            String name = tblData.getValueAt(row, 1).toString();
            String surname = tblData.getValueAt(row, 2).toString();
            String roomType = (String) tblData.getValueAt(row, 3).toString();
            String period = tblData.getValueAt(row, 4).toString();
            String days = tblData.getValueAt(row, 5).toString();
            String totalPrice = tblData.getValueAt(row, 6).toString();
            txtId.setText(id);
            txtName.setText(name);
            txtSurname.setText(surname);
            switch (roomType) {
                case "Superior":
                    rdoSuperior.setSelected(true);
                    break;
                case "Deluxe":
                    rdoDeluxe.setSelected(true);
                    break;
                case "Grand Deluxe":
                    rdoGrandDeluxe.setSelected(true);
                    break;
                case "Junior Suit":
                    rdoJuniorSuit.setSelected(true);
                    break;
                case "Family Junior Suit":
                    rdoFamilyJuniorSuit.setSelected(true);
                    break;
                case "Grand Family Suite":
                    rdoGrandFamilySuite.setSelected(true);
                    break;
            }
            switch (period) {
                case "Weekday (Sun - Thu)":
                    cbxWeek.setSelectedIndex(1);
                    break;
                case "Weekend (Fri - Sat)":
                    cbxWeek.setSelectedIndex(2);
                    break;
                default:
                    cbxWeek.setSelectedIndex(3);
                    break;
            }
            int day = Integer.valueOf(days);
            spnDays.setValue(day);
            tarResult.setText("ประเภทห้องพัก : " + roomType + "\n" + "ช่วงที่เข้าพัก : " + period + "\n"
                        + "จำนวนวันเข้าพัก : " + days + " วัน" + "\n" + "รวมราคา : " + totalPrice + " บาท");
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void spnDaysKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnDaysKeyTyped
        //No-Code
    }//GEN-LAST:event_spnDaysKeyTyped

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == java.awt.event.KeyEvent.VK_BACK_SPACE)
                || (c == java.awt.event.KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        char c = evt.getKeyChar();
        if (((c >= '0') && (c <= '9') || (c == '.')
                || (c == java.awt.event.KeyEvent.VK_BACK_SPACE)
                || (c == java.awt.event.KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtSurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurnameKeyTyped
        char c = evt.getKeyChar();
        if (((c >= '0') && (c <= '9') || (c == '.')
                || (c == java.awt.event.KeyEvent.VK_BACK_SPACE)
                || (c == java.awt.event.KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtSurnameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelReservation().setVisible(true);
            }
        });
    }

    public void clearText() {
        txtId.setText("");
        txtName.setText("");
        txtSurname.setText("");
        spnDays.setValue(0);
        cbxWeek.setSelectedIndex(0);
        tarResult.setText("");
        btnGroup.clearSelection();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxWeek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdoDeluxe;
    private javax.swing.JRadioButton rdoFamilyJuniorSuit;
    private javax.swing.JRadioButton rdoGrandDeluxe;
    private javax.swing.JRadioButton rdoGrandFamilySuite;
    private javax.swing.JRadioButton rdoJuniorSuit;
    private javax.swing.JRadioButton rdoSuperior;
    private javax.swing.JSpinner spnDays;
    private javax.swing.JTextArea tarResult;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
